# Preencha com os IPs do terraform output → targets → staging-*
all:
  children:
    staging:
      hosts:
        staging-1:
          ansible_host: PREENCHA_IP
        staging-2:
          ansible_host: PREENCHA_IP
      vars:
        env_name: staging
        cis_level: level2
